remote_theme: mmistakes/minimal-mistakes
color_scheme: auto
search_enabled: true
heading_anchors: true
title: "Nasc Documentation"
description: "Build reactive HTML frontends backed by server-side state."
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
nav_sort: case_insensitive
exclude:
  - ANNOYANCES.md
  - ROADMAP.md
  - sse-vs-websockets.md
  - initial-sketch/
  - nasc-review.md
